---
###############################################################################
# Configuration of OpenStack projects and users user environment.

# List of OpenStack domains. Format is as required by the stackhpc.os-projects
# role.
# openstack_domains:

# List of OpenStack projects. Format is as required by the stackhpc.os-projects
# role.
# openstack_projects:

###############################################################################
# Configuration of networks, subnets and routers for openstack.

# List of networks in the openstack system. Format is as required by the
# stackhpc.os-networks role.
openstack_networks:
  - "{{ openstack_network_external }}"
  - "{{ openstack_network_admin_tenant }}"
  - "{{ openstack_network_admin_vlan }}"
  - "{{ openstack_network_admin_provider }}"

# openstack external network name.
openstack_network_external_name: "external"

# openstack external network.
openstack_network_external:
  name: "{{ openstack_network_external_name }}"
  project: "admin"
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  provider_segmentation_id: 102
  shared: true
  external: true
  # Subnet configuration.
  subnets:
    - "{{ openstack_subnet_external }}"

# openstack external subnet.
openstack_subnet_external:
  name: "{{ openstack_network_external_name }}"
  project: "admin"
  cidr: "192.168.38.0/24"
  gateway_ip: "192.168.38.3"
  allocation_pool_start: "192.168.38.129"
  allocation_pool_end: "192.168.38.254"

# openstack admin tenant network name.
openstack_network_admin_tenant_name: "admin-tenant"

# openstack admin tenant network.
openstack_network_admin_tenant:
  name: "{{ openstack_network_admin_tenant_name }}"
  project: admin
  shared: false
  # Subnet configuration.
  subnets:
    - "{{ openstack_subnet_admin_tenant }}"

# openstack admin tenant subnet.
openstack_subnet_admin_tenant:
  name: "{{ openstack_network_admin_tenant_name }}"
  project: admin
  cidr: "10.1.0.0/24"
  gateway_ip: "10.1.0.1"
  allocation_pool_start: "10.1.0.2"
  allocation_pool_end: "10.1.0.254"

# openstack admin VLAN network name.
openstack_network_admin_vlan_name: "admin-vlan"

# openstack admin VLAN network.
openstack_network_admin_vlan:
  name: "{{ openstack_network_admin_vlan_name }}"
  project: admin
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  shared: false
  # Subnet configuration.
  subnets:
    - "{{ openstack_subnet_admin_vlan }}"

# openstack admin VLAN subnet.
openstack_subnet_admin_vlan:
  name: "{{ openstack_network_admin_vlan_name }}"
  project: admin
  cidr: "10.0.0.0/24"
  gateway_ip: "10.0.0.1"
  allocation_pool_start: "10.0.0.2"
  allocation_pool_end: "10.0.0.254"

# openstack admin provider VLAN network name.
openstack_network_admin_provider_name: "admin-provider"

# openstack admin provider VLAN
openstack_network_admin_provider:
  name: "{{ openstack_network_admin_provider_name }}"
  project: admin
  provider_network_type: "vlan"
  provider_physical_network: "physnet1"
  provider_segmentation_id: 100
  shared: false
  # Subnet configuration.
  subnets:
    - "{{ openstack_subnet_admin_provider }}"

# openstack admin provider VLAN subnet
openstack_subnet_admin_provider:
  name: "{{ openstack_network_admin_provider_name }}"
  project: admin
  cidr: "10.100.0.0/16"
  gateway_ip: "10.100.0.1"
  allocation_pool_start: "10.100.1.0"
  allocation_pool_end: "10.100.99.255"

# List of routers in the openstack admin project. Format is as required by the
# stackhpc.os-networks role.
openstack_routers:
  - "{{ openstack_router_admin }}"

# openstack admin router.
openstack_router_admin:
  - name: admin
    project: admin
    interfaces:
      - "{{ openstack_network_admin_vlan_name }}"
      - "{{ openstack_network_admin_tenant_name }}"
      - "{{ openstack_network_admin_provider_name }}"
    network: "{{ openstack_network_external_name }}"

# List of security groups in the openstack admin project.
# Format is as required by the stackhpc.os-networks role.
openstack_security_groups:
  # Default security group for the openstack admin project.
  - name: default
    project: admin
    rules:
      # Allow ICMP (for ping, etc.).
      - protocol: icmp
      # Allow SSH.
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22

# List of RBAC definitions in the openstack projct. Format is as required by the
# stackhpc.os-networks role.
# openstack_networks_rbac:

###############################################################################
# Configuration of nova flavors.

# List of nova flavors in the openstack project. Format is as required by the
# stackhpc.os-flavors role.
openstack_flavors:
  - "{{ openstack_flavor_m1_tiny }}"
  - "{{ openstack_flavor_m1_small }}"
  - "{{ openstack_flavor_m1_medium }}"
  - "{{ openstack_flavor_m1_large }}"
  - "{{ openstack_flavor_m1_xlarge }}"

# Virtual machine flavors.
openstack_flavor_m1_tiny:
  name: "m1.tiny"
  ram: 512
  disk: 1
  vcpus: 1

openstack_flavor_m1_small:
  name: "m1.small"
  ram: 2048
  disk: 20
  vcpus: 1

openstack_flavor_m1_medium:
  name: "m1.medium"
  ram: 4096
  disk: 40
  vcpus: 2

openstack_flavor_m1_large:
  name: "m1.large"
  ram: 8192
  disk: 40
  vcpus: 4

openstack_flavor_m1_xlarge:
  name: "m1.xlarge"
  ram: 16384
  disk: 100
  vcpus: 8

###############################################################################
# Configuration of nova host aggregates.

# List of nova host aggregates. Format is as required by the
# stackhpc.os_host_aggregates role.
# openstack_host_aggregates:

###############################################################################
# Configuration of Glance software images.

# List of Glance images. Format is as required by the stackhpc.os-images role.
openstack_images:
  - "{{ openstack_image_cirros_0_6_0 }}"

openstack_image_cirros_0_6_0:
  name: "cirros"
  type: qcow2
  image_url: "https://github.com/cirros-dev/cirros/releases/download/0.6.0/cirros-0.6.0-x86_64-disk.img"
  is_public: true
  properties:
    os_type: "linux"
    os_distro: "cirros"
    os_version: "0.6.0"
    hw_rng_model: "virtio"

# List of Diskimage Builder (DIB) elements paths to include in image builds.
# openstack_image_elements:

# List of Diskimage Builder (DIB) elements Git repositories to use in image
# builds.
# openstack_image_git_elements:

###############################################################################
# Configuration of Magnum container clusters.

# List of magnum cluster templates. Format is as required by the
# stackhpc.os-container-clusters role.
# openstack_container_clusters_templates:

###############################################################################
# Configuration variables for generating new Magnum cluster template config.

# These variables must be defined before using the generating new cluster
# templates - see repo README for more details.

# Must have at least 2 CPUs, 4GB RAM and 20GB disk
# magnum_default_master_flavor_name:
# magnum_default_worker_flavor_name:

# Network to create tenant cluster FIPs on
# magnum_external_net_name:

# Provider for cluster loadbalancers (e.g. 'ovn')
# magnum_loadbalancer_provider:

# Kubernetes CNI to use for cluster templates (defaults to 'calico')
# Must be one of the options supported by capi-helm-charts, see
# https://github.com/stackhpc/capi-helm-charts/tree/main/charts/cluster-addons#container-network-interface-cni-plugins
# magnum_default_network_driver:

# Whether to create a master nodes loadbalancer for cluster templates (defaults to 'True')
# magnum_master_lb_enabled:

# Whether to add a floating IP to the loadbalancer for cluster templates (defaults to 'True')
# magnum_cluster_floating_ip_enabled:

# List of nameservers to use for cluster templates
# magnum_cluster_default_dns_nameservers:

# Whether generated cluster templates should be public by default (defaults to 'True')
# magnum_cluster_templates_public:

###############################################################################
# Configuration variables for a CloudKitty ratings service deployment.

#     #    ###   #######  #####    IN ORDER TO SUCCESSFULLY DEPLOY CLOUDKITTY
# #   #   #   #     #     #        'cloudkitty.conf' & 'metrics.yml' MUST BE
#  #  #   #   #     #     ###      PROVIDED ALONGSIDE THE FOLLOWING CONFIG.
#   # #   #   #     #     #        MORE INFO CAN BE FOUND IN THE README.md
#     #    ###      #     #####    'stackhpc-kayobe-config' DOCS.
# A list where each item is a dictionary mapping the associated fields,
# with the 'mappings' field also being a list of dictionaries. Example
# of the mappings and their fields can be found below, however for more
# information please refer to the stackhpc.openstack.os_ratings role docs.
#
# openstack_ratings_hashmap_field_mappings:
#   - service: SERVICE_NAME
#     name: FIELD_NAME
#     mappings:
#       - value: MAPPING_VALUE
#         cost: MAPPING_COST
#         type: MAPPING_TYPE
#         group: MAPPING_GROUP <---THIS IS OPTIONAL---

# Much like the field mappings above, the service mappings are a list of
# dictionaries, however these are not associated with a field.
#
# openstack_ratings_hashmap_service_mappings:
#   - service: SERVICE_NAME
#     cost: MAPPING_COST
#     type: MAPPING_TYPE
#     group: MAPPING_GROUP <---THIS IS OPTIONAL---

###############################################################################
# Dummy variable to allow Ansible to accept this file.
workaround_ansible_issue_8743: true
